{
 "title": "NodeJS Response time Metrics Analytics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response time in seconds by seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rest_response_time_duration_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "restResponseTime"
    },
    {
     "expr": "sum(rate(db_response_time_duration_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "dbResponseTime"
    }
   ]
  },
  {
   "title": "Request more used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rest_response_time_duration_seconds_count",
     "legendFormat": "{{method}}: {{route}}"
    }
   ]
  },
  {
   "title": "Status code showed most frequently ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status_code) (rest_response_time_duration_seconds_count)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Request more used by time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(rest_response_time_duration_seconds_bucket{}[$__rate_interval])) by (method,route) * 50",
     "legendFormat": "{{method}}: {{route}}"
    }
   ]
  },
  {
   "title": "Status code by time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum (rate(rest_response_time_duration_seconds_count{}[$__rate_interval])) by (status_code) * 50",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Separate time response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "rest response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(rest_response_time_duration_seconds_bucket{}[$__rate_interval])) * 10",
     "legendFormat": "restResponse"
    }
   ]
  },
  {
   "title": "db response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(db_response_time_duration_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "db response time"
    }
   ]
  },
  {
   "title": "Obsolete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "API REST response time in milliseconds",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": " sum(rate(rest_response_time_duration_seconds_bucket{}[$__rate_interval]))",
       "legendFormat": "rest Response times"
      }
     ]
    }
   ]
  }
 ]
}